Repository filebrowser/filebrowser, pull requests merged in 2018-08, with the labels that each got.

#500 chore: move filebrowser/dev img to separate repo
  .travis.yml
  Dockerfile
  build/build_img.sh
  build/build_img_dev.sh
  dockerfiles/dev
Labels: in progress

#501 add pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: in progress

#485 Proxy Auth support
  cmd/filebrowser/main.go
  doc.go
  filebrowser.go
  http/auth.go
Labels: awaiting/review, enhancement, in progress

#508 Ensure that the config path provided through flags is used
  cmd/filebrowser/main.go
Labels: context/conf, in progress

#514 chore: fix author in push_rice
  build/push_ricebox.sh
Labels: in progress

#505 chore: use commit SHA as version if not release
  Gopkg.lock
  build/build.sh
  build/build_all.sh
Labels: build, enhancement, in progress

#506 [WIP] feat: use cobra to provide subcommands, move sources to lib
  .travis.yml
  Docker.json
  Gopkg.lock
  Gopkg.toml
  build/build.sh
  build/build_all.sh
  build/build_assets.sh
  build/push_ricebox.sh
  build/run_gometalinter.sh
  cli/cmd/db.go
  cli/cmd/root.go
  cli/cmd/rootalias.go
  cli/cmd/serve.go
  cli/cmd/server.go
  cli/cmd/version.go
  cli/main.go
  cmd/filebrowser/main.go
  lib/bolt/config.go
  lib/bolt/share.go
  lib/bolt/users.go
  lib/doc.go
  lib/file.go
  lib/filebrowser.go
  lib/http/auth.go
  lib/http/download.go
  lib/http/http.go
  lib/http/resource.go
  lib/http/settings.go
  lib/http/share.go
  lib/http/subtitle.go
  lib/http/users.go
  lib/http/websockets.go
  lib/staticgen/hugo.go
  lib/staticgen/jekyll.go
  lib/staticgen/staticgen.go
Labels: build, context/conf, enhancement, in progress

#515 fix search not working
  lib/http/websockets.go
Labels: in progress
